name: CI

on: [workflow_call]

jobs:
  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: check-for-cc
        id: hello
        uses: tanpatrick/conventional-commit-checker-action@master
